from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
import os, datetime, qrcode
from io import BytesIO

INV_DIR = os.path.expanduser("~/cybra_cloud_full/public/invoices")
os.makedirs(INV_DIR, exist_ok=True)

def qr_image(data: str):
    q = qrcode.QRCode(box_size=6, border=1)
    q.add_data(data); q.make(fit=True)
    b = BytesIO(); q.make_image(fill_color="black", back_color="white").save(b); b.seek(0)
    return ImageReader(b)

def generate_receipt(pay: dict) -> str:
    oid = pay.get("order_id", f"ORD{int(datetime.datetime.utcnow().timestamp())}")
    fn = os.path.join(INV_DIR, f"{oid}.pdf")
    c = canvas.Canvas(fn, pagesize=A4)
    w, h = A4
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, h-60, "CYBRA PAY — OFFICIAL RECEIPT")
    c.setFont("Helvetica", 11)
    y = h-100
    fields = [("ORDER", oid), ("AMOUNT", pay.get("amount")), ("CURRENCY", pay.get("currency","UAH")), ("METHOD", pay.get("method","cybra_pay"))]
    for k,v in fields:
        c.drawString(40, y, f"{k}: {v}"); y -= 18
    c.drawString(40, y, f"DATE: {datetime.datetime.utcnow().isoformat()}Z"); y -= 24
    payload = f"cybra://receipt?order_id={oid}&amount={pay.get('amount')}&ccy={pay.get('currency')}"
    c.drawImage(qr_image(payload), w-160, h-180, 120, 120)
    c.setFont("Helvetica-Oblique", 9); c.drawString(40, 60, "Generated by Cybra Cloud Full")
    c.showPage(); c.save()
    return fn

if __name__ == "__main__":
    print(generate_receipt({"order_id":"DEMO","amount":123.45,"currency":"UAH","method":"cybra_pay"}))
